### ISSUE TITLE
Special chars in comments are breaking the output

### ISSUE THREAD

**Issue by utrack** [gogo/letmegrpc#23]
If protobuf fields' comments contain any quote-like symbols then something usually breaks.
i.e. ` breaks go code and ' breaks javascript.

I'll fix it later if nobody else picks the issue up first,

**Comment by awalterschulze** [comment]
Thanks.  I have quite a lot on my plate at the moment.
The comments on the fields are used to generate user hints.  I can see how a ' can break this for the javascript.  I don't understand why ` would break the go code, but if it is breaking it should be investigated.

**Comment by utrack** [comment]
I understand :)
Well the whole HTML is stored verbatim in a variable with \`-quoted string, so if a string itself contains \` then it is considered as the trailing quote. This corrupts the generated go code.
