### ISSUE TITLE
undefined grpc.SupportPackageIsVersion3

### ISSUE THREAD

**Issue by commandus** [gogo/letmegrpc#31]
Last release

https://github.com/golang/protobuf/blob/master/protoc-gen-go/grpc/grpc.go#L51

uses

grpc.SupportPackageIsVersion4

**Comment by awalterschulze** [comment]
This should be fixed now
https://github.com/gogo/letmegrpc/commit/dd207bd0e74dd6f1945f60565aa50b6335954df7
