### ISSUE TITLE
RPC method name staring with lowercase character fails

### ISSUE THREAD

**Issue by commandus** [gogo/letmegrpc#32]
../../1.letmegrpc.go:8248: this.client.setVehicleModel undefined (type OneWayTicketClient has no field or method setVehicleModel, but does have SetVehicleModel)

if change setVehicleModel to SetVehicleModel, it works.

**Comment by awalterschulze** [comment]
Does this help?
https://github.com/gogo/letmegrpc/commit/b9b3c38abb9061cb6278f4129be2e0d684e30555

**Comment by awalterschulze** [comment]
No reply?
