### ISSUE TITLE
Support streaming methods

### ISSUE THREAD

**Issue by alenkacz** [gogo/letmegrpc#36]
It would be nice if streaming grpc methods will be supported

**Comment by awalterschulze** [comment]
I believe all combinations are tested
https://github.com/awalterschulze/goderive

Maybe you can give a more specific example that is breaking and how it is breaking?

**Comment by alenkacz** [comment]
not sure we both speak about the same thing. Just to be sure, I mean this http://www.grpc.io/docs/guides/concepts.html#server-streaming-rpc

**Comment by awalterschulze** [comment]
I think it is talking about the same thing

**Comment by rpliva** [comment]
I prepared simple example where proto file is
```
syntax = "proto3";

package test.proto;

service TestService {
    rpc NoStream(TestRequest) returns (TestResponse) {}
    rpc OutputStream(TestRequest) returns (stream TestResponse) {}
    rpc InputStream(stream TestRequest) returns (TestResponse) {}
    rpc BiStream(stream TestRequest) returns (stream TestResponse) {}
}

message TestRequest {
    string note = 1;
}

message TestResponse {
    string result = 1;
}
```

and when I use itI get following result

``````

**Comment by awalterschulze** [comment]
Seems there was a bug with Upstream and Bidirectional streams, where the method name was hardcoded.
This should fix it
https://github.com/gogo/letmegrpc/commit/f0b079aeb01a73ff4d0499dd6177c26cf8cc8399
Thanks for reporting :)
