### ISSUE TITLE
nested enums not generating a dropdown menu

### ISSUE THREAD

**Issue by con-ji** [gogo/letmegrpc#46]
I have a Protobuf message with an enum defined within it, e.g.
```message Test {
    enum TestEnum {
        SOME_OPTION = 1;
        SOME_OTHER_OPTION = 2;
    }
    required TestEnum test_enum = 1;
    ...
}
```
However, the GUI generated fails to provide a dropdown menu. Instead, it shows up as text, e.g.:
![screen shot 2018-06-04 at 4 39 00 pm](https://user-images.githubusercontent.com/20808671/40947114-de3fc528-6815-11e8-9611-e322b486b5d7.png)
Is there a fix?

**Comment by awalterschulze** [comment]
We have had problems with nested types before.
I am more than happy to a proper fix being contributed, but a quick fix would be to not embed the enum.

**Comment by con-ji** [comment]
I think the issue might be in `protoc-gen-gogo/descriptor/helper.go` in `getEnum()`: the inner for loop only iterates through non-nested enums and fails to check within messages for nested enums. I'll see if I can get this fixed in `protoc-gen-gogo`, unless someone finds a way to fix it in `letmegrpc/form`
