### ISSUE TITLE
Add tooltips to describe fields

### ISSUE THREAD

**Issue by jsgilmore** [gogo/letmegrpc#8]
It would be great if it was possible to annotate protobuf fields and have those fields appear as tooltips in the generated web form. This could be used to provide instructions and act as living documentation.

**Comment by awalterschulze** [comment]
field comments are now generated into the form as tooltips.
Also proto2's defaults are now filled into the form (proto3 does not have defaults).
@gpaul you might find this useful.

**Comment by awalterschulze** [comment]
I have made some backwards incompatible changes for custom fields, but the form_test.go shows how to use it with the new API.  This was necessary to get the comments.
